---
title: "BI410 Annotated Bibliography"
author: "Ali Carmichael"
date: "2025-05-07"
output:
  pdf_document: default
  html_document: default
---

The research question I will be using for my final project is: in years there were major climate change events did climate change beliefs, perceptions, and policy preferences change in any way? The data set I am interested in working with is the Climate Change in the American Mind: National Survey Data on Public Opinion (2008-2023). Yale Program on Climate Change Communication (YPCCC) & George Mason University Center for Climate Change Communication (Mason 4C). (2024). Climate Change in the American Mind: National survey data on public opinion (2008-2023) [Data file and codebook]. Which is survey data on public opinions of climate change that contains climate change beliefs and attitudes, risk perceptions, policy preferences and information acquisition behaviors. The data set also includes political party affiliation and sociodemographic information like age, gender, education, and income.

1.	Fritz, L., Baum, C. M., Brutschin, E., Low, S. & Sovacool, B. K. Climate beliefs, climate technologies and transformation pathways: Contextualizing public perceptions in 22 countries. Global Environmental Change 87, 102880 (2024).

In this article by Fritz et al., the authors discuss how the public's perception, attitudes, and beliefs, of climate action like carbon removal and solar radiation in political policies is shaped by their personal belief of experiencing harm from climate change. The authors gathered data from previous surveys that were conducted in 22 different countries where respondents could give their different perceptions of climate change problems and their proposed solutions. From their analysis of the data collected in these surveys the authors determined that climate harm and worry about climate change are good indicators of the support for climate change policies, and public support for climate-intervention hinges on credible climate action that addresses the root causes of these problems. However, this study only used data from 22 large and populated countries missing many of the smaller African and Asian countries which leaves out a large portion of the world and their view on climate change and policies. 
By using this article I can better understand how attitudes around climate change and solutions fluctuate after climate disasters or extreme weather events. I can also compare results from the data I will be using to data from this study and see if there are any similar trends in our findings. 

2.	Mase, A. S., Gramig, B. M. & Prokopy, L. S. Climate change beliefs, risk perceptions, and adaptation behavior among Midwestern U.S. crop farmers. Climate Risk Management 15, 8–17 (2017).

Mase et al., discusses the effect of climate change policies on Midwestern farmers in the U.S. and in particular, how their beliefs and attitudes effect their willingness for adaptation to policies. The authors used a 2012 survey of 5000 corn farmers across 22 different Midwestern Watersheds to analyze the most common management strategies, farmer's beliefs in climate change, perceptions of changing weather, climate risk, and attitudes. They found that farmer's perception of risk to their own farms and crops was an important factor in determining willingness for adaptation to new management strategies and policies. This study is from 2017 and is a few years old, while still relevant it is a limitation and it would be interesting to see if any of these findings changed in more recent years. 
This article discusses how risk is an important factor for determining whether someone is more open to climate change policies and management strategies which could be used as supporting evidence if I was to find similar patterns between extreme weather events and support for climate change policies in my data.

3.	Gould, R. K., Shrum, T. R., Ramirez Harrington, D. & Iglesias, V. Experience with extreme weather events increases willingness-to-pay for climate mitigation policy. Global Environmental Change 85, 102795 (2024).

In this article by Gould et al., the authors explore how extreme weather events influence climate policy support in the U.S. The authors use self-reports of extreme weather event experience in combination with actual weather data, a willingness-to-pay measure to assess behavior, and an analysis of which weather events have stronger impacts on people. The authors found that people who report experiencing an extreme weather event are willing to pay approximately $112/year more for climate change policies than those who do not, with wildfires having the strongest influence. One limitation of this study is that they use self-reporting which could be potentially biased, however, the authors control for this by comparing it to actual weather data.
This article could be useful to compare the data I have because there is no variable in my data that determines how much more a person is willing to pay for policy, just how they feel about certain policies and political parties.

4.	Binelli, C., Loveless, M. & Schaffner, B. F. Explaining Perceptions of Climate Change in the US. Political Research Quarterly 76, 365–380 (2023).

Binelli et al., investigates whether experience with changes in local climate and weather patterns can override the strong feelings of loyalty to a particular political party when it comes to climate change policies. The authors used both individual level data and country level data on local climate change and found that while experience with local changes in weather can significantly impact perceptions, political ideology remains the strongest effect on support of climate change policy. One limitation of this study is that the survey data lists race as either White, Black, Hispanic, Or Other which misses a large portion of Americans that might help us determine if there are patterns in beliefs among different demographics.
This data is very similar to what I would like to do for my project so it can help me figure out how to analyze and visualize my data and it will also be good for comparison. 

5.	Hai, Z. & Perlman, R. L. Extreme weather events and the politics of climate change attribution. Science Advances 8, eabo2190 (2022).

Hai et al. investigate how adults in America view politicians who attribute extreme weather events like wildfires and floods to climate change. In particular, they want to determine the hesitance for politicians to respond to climate change and push for management strategies. The authors found that Republicans perceive political officials who link extreme weather events to climate change as less capable of addressing weather related disasters and become less supportive of efforts to protect against similar disasters in the future. A limitation of this study is that the survey metrics they used were to answer questions on a scale, usually 0-4 which might not be the most descriptive and it's possible that these responses could change with a larger more descriptive scale.
This study is helpful because the authors specifically looked at political party affiliation and it's influence on climate change policies in combination with extreme weather events which is similar to my project. This can be used to compare my results to and back up certain patterns I find in my project.

6.	Poortinga, W., Demski, C. & Steentjes, K. Generational differences in climate-related beliefs, risk perceptions and emotions in the UK. Communications Earth & Environment 4, 229 (2023).

The study conducted by Poortinga et al., investigates the correlation between age and their beliefs and emotions about climate change. The authors used three different surveys from the UK in 2020, 2021, and 2022 to determine if there were higher levels of climate-related beliefs, risk perceptions, and emotions among younger generations. They found that while there is a gap, generational differences are mainly in emotional engagement rather than in beliefs about climate change due to the more consistent climate-related beliefs and risk perceptions in generations. This study was conducted in the UK so while helpful for determining patterns across demographics like age, it cannot be directly applied to America.
This article will be helpful in understanding trends in demographics like age in the climate beliefs and attitudes data set that I will be using, it will also be interesting to look at when comparing it to the differences among generations in America.

7.	Capstick, S., Whitmarsh, L., Poortinga, W., Pidgeon, N. & Upham, P. International trends in public perceptions of climate change over the past quarter century. WIREs Climate Change 6, 35–61 (2015).

Capstick et al., uses a systematic review to understand the changes in public perceptions of climate change over time in different nations using a combination of surveys and studies carried out over long timescales and statistical analyses. The authors found that due to an imbalance in climate change research in a polling in Western developed nations there are many unknowns in climate change perception progression worldwide. This article does a good job addressing the lack of data in less developed countries and the overwhelming amount of data in Western countries that is then used to explain climate change perception for the rest of the world.
This article will help with pointing out the limitations in the data set I will be using and how it can only be used to understand trends in America not the entire world. It also offers a lot of similar data in other countries that I can use to compare my findings and visualizations to.

8.	Spence, A., Poortinga, W., Butler, C. & Pidgeon, N. F. Perceptions of climate change and willingness to save energy related to flood experience. Nature Climate Change 1, 46–49 (2011).

Spence et al., uses national survey data collected from 1,822 individuals in the UK to examine the link between experience with flood disasters and perceptions of climate change and their ability and willingness to reduce energy use. The authors found that those who report experience of flooding express more concern over climate change and feel more confident in their ability to act and reduce energy usage. One limitation of this study is that it was conducted in 2011 and while still interesting may not be as relevant as some of the other articles I will use.
This article highlights a link between local weather events and an increase in concern for climate change action which can be used to support similar findings from my project. It also has helpful visualizations that can help inspire me for my final project. 

9.	Dietz, T. Political events and public views on climate change. Climatic Change 161, 1–8 (2020).

The author of this article discusses the outcome of political party wins and their effect on public views of climate change. The author discusses how Trump's presidency tended to reduce climate beliefs among supporters whole increasing them in opponents, leading to and increase in willingness to take action. The author suggests that understanding the effect of social change and how it plays a roll in climate change action is incredibly important. A limitation of this article is that the author has not collected or used any public data for analysis.
This article could be used to explain some of the possible trends I see in the willingness to take action or support of climate change policies in people of the opposite political party of who is currently in office of the year where extreme weather events happen.

10.	Visconti, G. & Young, K. The effect of different extreme weather events on attitudes toward climate change. PLOS ONE 19, (2024).

The authors of this article use survey to analyze individual-level data in the U.S to determine whether extreme weather events like severe storms, floods, fires, and hurricanes impact attitudes towards climate change. They found that exposure to only one extreme weather event, fires, has a small significant impact on acknowledging the existence of climate change and the support  to take action. One important part of this study is that they assessed several different types of extreme weather events not just one and they found that the impact that fires had on climate change beliefs was not long term.
This article will be helpful for my project because they used survey data from the U.S. in combination with extreme weather data for many different extreme weather events which is similar to my project. They also found that while fires had a significant impact it was not long-term which I anticipate will also show up in my project so I can use this to support my findings if I see that, or use it as a comparison if I find something different. 
